# --------- environment
server:
  port: 8081
  # servlet:
  #   context-path: /test

# --------- log
logging:
  level:
    org:
      springframework:
        data: trace
        jdbc:
          core:
            JdbcTemplate: debug
        security: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      abt: TRACE
      camunda: debug
    # sql: trace
    web: DEBUG

spring:
  # 显示 SQL 语句
  jpa:
    show-sql: true
    # 格式化 SQL 语句
    properties:
      hibernate:
        format_sql: true
        
  # --------- datasource
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=zjdata;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: sasa
    # password: abt@23328
    type: com.zaxxer.hikari.HikariDataSource
    
  # --------- messages
  messages:
    basename: i18n/message

# ---- camunda wf
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true
    auto-deployment-enabled: true
    job-execution:
      enabled: false

# --------- file
com:
  abt:
    file:
      upload:
        save: E:\\upload
        temp: temp-attachments

# ---------- spring doc/swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# --------- webapi
webapi:
  http:
    ip: localhost
    port: 52789
    base: /api
    protocol: http://
    token:
      key: X-Token
    uri: http://localhost:52789/api
    # uri: http://192.168.0.181:52789/api
    # ip: 7386n59g91.goho.co
    # port: 10008
    # uri: http://7386n59g91.goho.co:10008/api

# ----- fieldwork excel model
abt:
  fw:
    excel:
      output: E:\\fw_atd\\
    export:
      template: E:\\fw_atd\\fieldwork_atd_model2.xlsx
      tempfile:
        path: E:\\fw_atd\\fw_export.xlsx
  
  # ------ app
  app:
    bak:
      android:
        dir: /05_app_bak/android/
      ios:
        dir: /05_app_bak/ios/
    run:
      android:
        url: /05_app_bak/run/android_apk.apk
      ios:
        url: /05_app_bak/run/ios_apk.apk
      dir: /05_app_bak/run/
  
  # ---- templates
  rbs:
    excel:
      template: C:\\Users\\Administrator\\Desktop\\rbs_template.xlsx
    pur:
      dir: C:\\Users\\Administrator\\Desktop\\temp\\
  
  pay:
    excel:
      template: C:\\Users\\Administrator\\Desktop\\pay_template.xlsx
      
  pur:
    excel:
      template: C:\\Users\\Administrator\\Desktop\\purchase_apply_template.xlsx
    accept:
      excel:
        template: C:\\Users\\Administrator\\Desktop\\purchase_accept_template.xlsx
    tmp:
      name: purchase.xlsx
      
  temp:
    dir: C:\\Users\\Administrator\\Desktop\\temp\\
  
  # ---- signature
  sig:
    dir: F:\\sig\\ 